try:
  print(x)
except:
  print("Something went wrong")
else:
  print("bruh")
finally:
  print("The 'try except' is finished")